#Usage:
# ./1_bench.sh perf
# ./1_bench.sh submit <team_name> (runs perf + submits to leaderboard)

LB_URL="https://daniehua-agent-leaderboard.hf.space"


# Check team name for submit mode
if [ $1 == "submit" ]; then
    if [ ! -z "$2" ]; then
        TEAM_NAME="$2"
    elif [ ! -z "$TEAM_NAME" ]; then
        TEAM_NAME="$TEAM_NAME"
    else
        echo "ERROR: Team name required for submit mode"
        echo "Usage: ./1_bench.sh submit <team_name>"
        echo "Or set TEAM_NAME environment variable"
        exit 1
    fi
    echo "INFO: Using team name: $TEAM_NAME"
fi


if [ $1 == "perf" ] || [ $1 == "submit" ]; then
    echo "INFO: perf"
    date=$(date +'%b%d_%H_%M_%S')
    if [ ! -z "$PATH_TO_KERNEL_FILE" ]; then
        PATH_TO_KERNEL_FILE="$PATH_TO_KERNEL_FILE"
    else
        echo "ERROR: PATH_TO_KERNEL_FILE required for perf or submit mode, should be xxxxx.json generated by your agent "
        echo "Pls set PATH_TO_KERNEL_FILE environment variable"
        exit 1
    fi
    echo "INFO: benching kernels in $PATH_TO_KERNEL_FILE"

    geak-eval -f $PATH_TO_KERNEL_FILE -o out.json -ds tbg
    result=${PATH_TO_KERNEL_FILE:0:${#PATH_TO_KERNEL_FILE}-5}
    suffix1="/out.json"
    suffix2="_perf_0.json"
    perf_file="$result$suffix1$suffix2" # reflexion_oneshot_tritonbench_9/out.json_perf_0.json
    PERF_OUTPUT=$(python show_results.py --path $perf_file)
    echo "$PERF_OUTPUT"
fi



if [ $1 == "submit" ]; then
    # if [ ! -z "$PERF_OUTPUT" ]; then
    #     PERF_OUTPUT="$PERF_OUTPUT"
    # else
    #     echo "ERROR: perf mode required before submit mode"
    #     echo "Usage: 1. ./1_bench.sh perf <iteration id> 2. ./1_bench.sh submit <team_name>"
    #     exit 1
    # fi

    echo "INFO: Submitting results for team: $TEAM_NAME"

    PERF_LINE=$(echo "$PERF_OUTPUT" | grep -E "[0-9]+\.[0-9]+.*" | tail -1)
    # SPEEDUP=$(echo "$PERF_LINE" | awk -F',' '{gsub(/^[[:space:]]+|[[:space:]]+$/, "", $1); print $1}')     # Convert ms to seconds
            
    # Default to 0.0 if parsing fails
    # CALL_ACC=${CALL_ACC:-0.0}
    # EXEC_ACC=${EXEC_ACC:-0.0}
    # SPEEDUP1=${SPEEDUP1:-0.0}
    
    echo "Performance metrics:"
    echo "  speedup for kernels: ${PERF_LINE} times"
    echo "  your total score is: ${PERF_LINE}"
    
    # Submit to leaderboard
    echo "Submitting to leaderboard..."
    curl -X POST $LB_URL/gradio_api/call/submit_results -s -H "Content-Type: application/json" -d "{
        \"data\": [
            \"$TEAM_NAME\",
            $PERF_LINE
        ]
    }" | awk -F'"' '{ print $4}' | read EVENT_ID

    sleep 2

    echo "SUCCESS: Results submitted to leaderboard! 🤗 Check it out @ $LB_URL"
fi
